name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/main.tex
      - name: Copy pdf file
        run: mkdir -p github_deploy && cp build/main.pdf github_deploy
      - name: Release
        if: startsWith(github.ref, 'refs/tags/') # Only create a release when pushing to a tag
        uses: softprops/action-gh-release@v1
        with:
          files: github_deploy/main.pdf
      - name: Deploy on orphan branch
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: pdf
          force_orphan: true
